// Codegen: build a compile-safe map from the app's Hugeicons glyphs to their
// Material Icons equivalents (Outlined / Rounded / Sharp), so the theme's
// icon-style axis can render an alternate style. The app's AppIcons names are
// Material-derived (chevronRightRounded, errorOutlineRounded, …), so we derive
// the Material base from the FIELD NAME and only emit variants that actually
// exist in the installed Flutter SDK — anything unmapped falls back to Hugeicons.
//
// Run from `frontend/`:  dart run tool/gen_material_icons.dart
//
// Emits: lib/core/icons/app_icons_material.g.dart

import 'dart:io';

const _materialIconsPath =
    '/opt/homebrew/share/flutter/packages/flutter/lib/src/material/icons.dart';
const _appIconsPath = 'lib/core/icons/app_icons.dart';
const _outPath = 'lib/core/icons/app_icons_material.g.dart';

const _styleTokens = {'rounded', 'sharp', 'outlined', 'outline', 'filled'};

String _camelToSnake(String s) {
  final b = StringBuffer();
  for (var i = 0; i < s.length; i++) {
    final c = s[i];
    final isUpper = c.toUpperCase() == c && c.toLowerCase() != c;
    final isDigit = RegExp(r'[0-9]').hasMatch(c);
    if (i > 0 && (isUpper || (isDigit && !RegExp(r'[0-9]').hasMatch(s[i - 1])))) {
      b.write('_');
    }
    b.write(c.toLowerCase());
  }
  return b.toString();
}

void main() {
  // 1. Valid Material icon names.
  final matSrc = File(_materialIconsPath).readAsStringSync();
  final valid = <String>{};
  for (final m
      in RegExp(r'static const IconData ([a-z][a-z0-9_]*)').allMatches(matSrc)) {
    valid.add(m.group(1)!);
  }

  // 2. App icons: field -> HugeIcons const. Collapse newlines first.
  final appSrc = File(_appIconsPath).readAsStringSync().replaceAll(RegExp(r'\s+'), ' ');
  final entries = <(String field, String glyph)>[];
  for (final m in RegExp(
    r'static const AppIconData (\w+) = HugeIcons\.(\w+);',
  ).allMatches(appSrc)) {
    entries.add((m.group(1)!, m.group(2)!));
  }

  String? pick(String name) => valid.contains(name) ? name : null;

  // 3. For each unique glyph, derive the Material base + variants.
  final seenGlyph = <String>{};
  final rows = <String>[];
  var mapped = 0;
  for (final (field, glyph) in entries) {
    if (!seenGlyph.add(glyph)) continue; // one entry per underlying glyph
    final snake = _camelToSnake(field);
    // Candidate bases: progressively strip trailing style tokens, shortest first.
    final tokens = snake.split('_');
    final candidates = <String>[];
    final t = [...tokens];
    candidates.add(t.join('_'));
    while (t.isNotEmpty && _styleTokens.contains(t.last)) {
      t.removeLast();
      if (t.isNotEmpty) candidates.add(t.join('_'));
    }
    // Prefer the shortest fully-stripped base that has any Material variant.
    String? base;
    for (final c in candidates.reversed) {
      if (pick(c) != null ||
          pick('${c}_outlined') != null ||
          pick('${c}_rounded') != null ||
          pick('${c}_sharp') != null) {
        base = c;
        break;
      }
    }
    if (base == null) continue;
    final outlined = pick('${base}_outlined') ?? pick(base);
    final rounded = pick('${base}_rounded') ?? pick(base);
    final sharp = pick('${base}_sharp') ?? pick(base);
    if (outlined == null && rounded == null && sharp == null) continue;
    String v(String? n) => n == null ? 'null' : 'Icons.$n';
    rows.add(
      '  AppIcons.$field: (outlined: ${v(outlined)}, rounded: ${v(rounded)}, sharp: ${v(sharp)}),',
    );
    mapped++;
  }

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/gen_material_icons.dart — do not edit by hand.')
    ..writeln('// Maps the app\'s Hugeicons glyphs to Material Icons variants so')
    ..writeln('// the theme icon-style axis can render Outlined / Rounded / Sharp.')
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln("import 'package:shopxy/core/icons/app_icons.dart';")
    ..writeln()
    ..writeln('/// Material equivalents for one app glyph (null = no such variant).')
    ..writeln('typedef MaterialIconSet = ({IconData? outlined, IconData? rounded, IconData? sharp});')
    ..writeln()
    ..writeln('/// Keyed by the const [AppIcons] glyph (const canonicalisation makes')
    ..writeln('/// identity lookup work). Unmapped glyphs fall back to Hugeicons.')
    ..writeln('const Map<AppIconData, MaterialIconSet> kMaterialIconMap = {');
  for (final r in rows) {
    buf.writeln(r);
  }
  buf.writeln('};');

  File(_outPath).writeAsStringSync(buf.toString());
  stdout.writeln('Mapped $mapped / ${seenGlyph.length} unique glyphs → $_outPath');
}
